xaf/omni

- README.md
Small issues running through the install on my arch install: `ruby-build` is a distinct package and I got an incorrect error about rbenv being out of date when it wasn't installed. When I update the installer to look for `ruby-build` it gave me a wonky explanation that I needed to install
```
-
```
because the list of packages required is obviously not populated for arch/pacman because it's not a known package manager. Makes more sense to me to just tell users on unknown systems what executables are being looked for and leaving it on them to figure out how to provide them.
> 📝 Improve README details about configuration

- README.md
- install.sh
This moves the fish config from `config.fish` into `conf.d/omni.fish` to make the install a bit more fish-y. Fish config docs are available [here](https://fishshell.com/docs/current/language.html#configuration-files).
> Move fish config into conf.d directory

- Cargo.lock
- Cargo.toml
- src/internal/config/config_value.rs
- src/internal/config/mod.rs
- src/internal/config/parser.rs
- src/internal/config/up/utils.rs
- src/internal/git/updater.rs
- src/internal/mod.rs
- src/internal/self_updater.rs
As was done in the ruby version, omni will offer to auto-update when a new version is published. This by default will be queried to the user, but can be configured (`path_repo_updates.self_update`) to never happen (`false`), happen automatically (`true`) or keep asking (`ask`, which is the default).
The update will work for binary installs, having the binary download the new version tarball, check against the sha256 for integrity, and replace itself. It will also work for brew installs, where the binary will simply call `brew upgrade xaf/omni/omni` to trigger an upgrade of itself.
Closes https://github.com/XaF/omni/issues/24
> ✨ Add self updater for omni

- src/internal/cache.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/up.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/error.rs
- src/internal/mod.rs
This allows to avoid updating more than once a day, and checking for available versions more than once an hour. This thus allows for multiple successive 'up' commands to be faster, even more when doing auto-updates of many repositories.
> ✨ Add caching for asdf updates and plugin versions

- src/internal/cache/handler.rs
- src/internal/cache/repositories.rs
- src/internal/commands/builtin/up.rs
- src/internal/config/config_value.rs
- src/internal/config/parser.rs
- website/contents/reference/01-configuration/0102-parameters/0102-overview.md
- website/contents/reference/01-configuration/0102-parameters/010250-up_command.md
This allows to take fingerprints of the contents of `suggest_config` and `suggest_clone` when bootstrapping a repository. No matter what the user decides to do, it saves that fingerprint and compares it on future runs, allowing to track any change to those from the repository point of view, which would warrant suggesting the changes again to the use.
This also introduces a new `up_command/auto_bootstrap` boolean configuration parameter to now default to `omni up --bootstrap` when running `omni up`, and thus automatically suggesting changes whenever the repository suggestions get updated.
Closes https://github.com/XaF/omni/issues/66
> feat: ✨ Add `suggest_config` and `suggest_clone` fingerprints

- .github/workflows/build.yaml
Closes https://github.com/XaF/omni/issues/135
> build(linux): 👷 move to `musl` for the linux binaries

- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/fromconfig.rs
- src/internal/commands/path.rs
- src/internal/config/config_value.rs
- src/internal/config/loader.rs
- src/internal/config/parser.rs
- src/internal/git/mod.rs
- src/internal/git/org.rs
- src/internal/git/updater.rs
- src/internal/git/utils.rs
- website/contents/reference/01-configuration/0102-parameters/010250-path.md
- website/contents/reference/02-builtin-commands/0250-cd.md
- website/contents/reference/02-builtin-commands/0250-clone.md
- website/contents/reference/02-builtin-commands/0250-tidy.md
This might include **breaking changes** in terms of the behaviors of some commands.
Packages are a stable, non-development copy of a git repository that can be used for providing commands in a stable way. Those repositories will be cloned in a different (data) directory than the development repositories, and will be loaded in the omnipath as a simple package reference, e.g.
```
path:
append:
- package: git@github.com:XaF/omni
path: cmd
```
This will be handled the same way as the regular omnipath is, except that it won't be in your development directories. Use this approach for repositories that provide you commands, but that you don't expect to develop with. You can also use this as to have a stable copy of a repository, even if that repository also exists in your development …
> feat: ✨ Add support for 'packages'

- src/internal/commands/base.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/loader.rs
- src/internal/commands/mod.rs
- src/internal/commands/void.rs
`omni help` can become pretty long as commands and categories get added. This changes the help message to fold subcommands into their parents when more than one command is provided for a specific path.
This also adds support for `omni help <command>` where `<command>` does not exist but is a path leading to existing command(s). In such situation, this will show the subcommands valid for that path.
This also allows for `omni <command>` where `<command>` does not exist but is a path leading to existing command(s) to show a `Did you mean` message suggesting the given subcommands.
Closes https://github.com/XaF/omni/issues/20
> feat: ✨ `omni help` now folds subcommands

- src/internal/commands/base.rs
- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/builtin/hook.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/frompath.rs
- src/internal/commands/void.rs
- src/internal/config/parser.rs
Arguments and options were two separate lists and are now handled as a single list, allowing to keep the order of parameters as provided.
Closes https://github.com/XaF/omni/issues/181
> chore(refactor): arguments and options are now a list

- Cargo.lock
Updating `Cargo.lock` with `cargo update`
The following crate dependencies are to be updated:
- [`chrono-tz`](https://crates.io/crates/chrono-tz) ([`v0.8.3`](https://docs.rs/chrono-tz/0.8.3/) -> [`v0.8.4`](https://docs.rs/chrono-tz/0.8.4/))
- [`chrono-tz-build`](https://crates.io/crates/chrono-tz-build) ([`v0.2.0`](https://docs.rs/chrono-tz-build/0.2.0/) -> [`v0.2.1`](https://docs.rs/chrono-tz-build/0.2.1/))
> chore(deps): 📦 cargo update

- src/internal/commands/builtin/help.rs
- website/contents/reference/02-builtin-commands/0250-help.md
Since 74463b9 (#182) the commands are folded by default in `omni help`; this allows to pass a `--unfold` flag to the help command in order to see all commands.
> feat(help): ✨ add `--unfold` flag to show all commands

- website/contents/reference/01-configuration/0102-parameters/010250-clone.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-apt.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-dnf.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-pacman.md
Some of the features that were available in the ruby version of omni haven't been ported yet to the rust version.
This adds links to the issues tracking the addition of those features in the documentation.
> docs: 📝 Add issue links for missing features

- src/internal/commands/base.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/mod.rs
- src/internal/commands/builtin/config/path/mod.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/hook/base.rs
- src/internal/commands/builtin/mod.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/loader.rs
- src/internal/config/config_value.rs
- src/internal/config/parser.rs
- src/internal/env.rs
- src/internal/git/mod.rs
- src/internal/git/org.rs
- src/internal/git/updater.rs
- src/internal/git/utils.rs
- src/internal/mod.rs
- website/contents/reference/02-builtin-commands/02-overview.md
- website/contents/reference/02-builtin-commands/0250-config/0250-path/0250-switch.md
This command allows to easily switch a repository between worktree and package modes. The command usage is as follows:
```sh
omni config path switch [--package|--worktree] [repo]
```
If none of `--package` or `--worktree` is provided, the command will simply toggle the source of the repository. If `repo` is not provided, the current directory will be used.
The command errors out if:
- No `repo` is provided and the current directory is not a repository
- The `repo` is not found, or cannot be resolved
- The repository is not currently cloned (at all)
Closes https://github.com/XaF/omni/issues/196
> feat: ✨ add new `config path switch` command

- src/main.rs
- website/contents/reference/03-custom-commands/03-overview.md
So far, it was possible to use the help command to check if a command existed, as it would return exit code 1 if the command was not found:
$ omni help <command>
With the support for the folded help, it now requires slightly more logic as there are auto-generated sections for elements leading to the path of an existing command:
$ omni help config 2>&1 | grep '^Source:' | grep -qv 'auto-generated'; echo $?
1
$ omni help config path switch 2>&1 | grep '^Source:' | grep -qv 'auto-generated'; echo $?
0
This introduces a new `--exists` flag which aims specifically at checking if a subcommand indeed exists:
omni --exists <command>
This flag does not return anything on stdout or stderr, but has a 0 or 1 exit code, depending if the subcommand exists or does not exist, respectively.
Closes …
> feat: ✨ add `--exists` flag to check if command exists

- .github/workflows/cargo-dependencies.yaml
- website/docusaurus.config.js
This is required to use the `gh` command line in a github action, and was the missing piece for the cargo dependencies auto-updater to work as expected.
> build(cargo dependencies): 👷 fix passing the github token as env var

- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/scope.rs
- src/internal/config/bootstrap.rs
- src/internal/env.rs
Omni's installation require setting up the shell integration. As part of https://github.com/XaF/omni/issues/179 we made an install script available to make it easy to install omni in a few instants, and as part of https://github.com/XaF/omni/pull/209 we added the `config bootstrap` command to bootstrap omni's configuration. This now adds automatic addition of omni's shell integration to the rc file of the caller, which will make it even easier to get started with omni.
Closes https://github.com/XaF/omni/issues/210
> feat: ✨ add shell integration during bootstrap

- .github/workflows/release.yaml
- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/loader.rs
- src/internal/config/bootstrap.rs
- src/internal/config/up/bundler.rs
- src/internal/config/up/custom.rs
- src/internal/config/up/homebrew.rs
- src/internal/config/up/utils.rs
- src/internal/env.rs
- src/internal/git/org.rs
- src/internal/git/updater.rs
- src/internal/self_updater.rs
- src/internal/user_interface/colors.rs
- src/internal/user_interface/print.rs
- src/main.rs
The `StringColor` trait was only implemented for String objects, which required to call `.to_string()` on many objects before coloring them. This fixes that by making that trait work on any object that implements the `ToString` trait.
> refactor(StringColor): make it work for all string-like objects

- .github/workflows/auto-pr-cargo-dependencies.yaml
- .github/workflows/auto-pr-cargo-fixes.yaml
- .github/workflows/auto-pr-yarn-dependencies.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
This avoids having to keep a unique, not-as-secure token for those operations, and instead use an `omnicli`'s org github app to handle those operations.
> build(auth): 👷🔐 use github app tokens for operations requiring a token

- src/internal/commands/builtin/hook/init.rs
- src/internal/config/parser.rs
- website/contents/reference/01-configuration/0102-parameters/0102-overview.md
- website/contents/reference/01-configuration/0102-parameters/010250-shell_aliases.md
- website/contents/reference/01-configuration/0102-parameters/010250-up_command.md
This allows to configure the shell aliases that the init hook will inject directly from the configuration file instead of only supporting it from the command line parameters.
This adds the following configuration option:
```yaml
shell_aliases:
- o
- alias: o2
- alias: ocd
target: cd
```
Closes https://github.com/XaF/omni/issues/195
> feat: ✨ Add configuration of the shell aliases for the init hook

- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/loader.rs
- src/internal/commands/path.rs
- src/internal/commands/utils.rs
- src/internal/config/config_value.rs
- src/internal/config/loader.rs
- src/internal/config/parser.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/bundler.rs
- src/internal/config/up/custom.rs
- src/internal/config/up/homebrew.rs
- src/internal/env.rs
- src/internal/git/org.rs
- src/internal/git/updater.rs
- src/internal/git/utils.rs
- src/internal/mod.rs
- src/internal/self_updater.rs
- src/internal/user_interface/colors.rs
- src/internal/workdir.rs
This allows to only load the required environment variables when we need them, instead of loading the whole structure anytime any of the variables is needed.
Closes https://github.com/XaF/omni/issues/29
> refactor(env): ♻️  decommission the env struct in favor of lazy_static

- src/internal/config/up/custom.rs
- src/internal/config/up/error.rs
- src/internal/config/up/utils.rs
- src/internal/git/updater.rs
For some operations such as `custom` operations when calling `omni up`, the previous message was a bit cryptic. It will now print simply the exit code and a path to a saved log file. Most subprocesses that are called in the background for a better UX will hence have their logs saved in a way that makes it easier to understand what happened when an execution failed.
> feat: ✨ save log files when subprocesses fail

- Cargo.lock
- Cargo.toml
- src/internal/cache/omnipath.rs
- src/internal/commands/base.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/config/config_value.rs
- src/internal/config/parser.rs
- src/internal/config/up/utils.rs
- src/internal/env.rs
- src/internal/git/mod.rs
- src/internal/git/updater.rs
- src/internal/self_updater.rs
- src/internal/user_interface/mod.rs
- src/internal/user_interface/print.rs
- src/internal/workdir.rs
- src/main.rs
- website/contents/reference/01-configuration/0102-parameters/010250-path_repo_updates/010250-self.md
This will make it smoother to use omni as only the required updates will be done synchronously (i.e. if the command being run is from the path to be updated), while other updates will be done asynchronously in the background.
For asynchronous updates, the log file will be saved in case of any error, and printed the next time the `env` hook is being called.
Closes https://github.com/XaF/omni/issues/170
> feat(updates): ✨ add support for background updates

- src/internal/config/config_value.rs
- src/internal/config/parser.rs
- src/internal/git/updater.rs
- website/contents/reference/01-configuration/0102-parameters/010250-path_repo_updates/010250-self.md
When doing updates, multiple `git pull` are being done in parallel, which can be bothersome if using a password on the ssh key or a ssh agent with authentication, since with multiple parallel queries, the user will have to give multiple approvals.
This adds a pre-auth step when doing updates that will run a `ls-remote` on each individual host found in the repositories to trigger the authentication process. Failed auth will lead to skipping updates for repositories in that host.
> fea(updater): ✨ pre-auth to hosts to avoid multiple auth queries

- src/internal/commands/base.rs
- src/internal/commands/frompath.rs
With the handling of aliases for symlinks, the execution path was lost and the first encountered path was the one being executed for any of the aliases to one command. This prevented being able to use `$0` in bash scripts for instance, or any equivalent in any language when writing an omni command.
This fixes that problem by making sure that aliases that have their own execution path, which is the case for symlinks, are being executed from that path, making `$0` (and equivalents) usable.
Fixes https://github.com/XaF/omni/issues/161
> fix(path commands): 🐛 make the exec path accurate

- src/internal/cache/asdf_operation.rs
- src/internal/cache/homebrew_operation.rs
- src/internal/cache/utils.rs
- src/internal/config/up/homebrew.rs
A cache has been added for the asdf operations when running `omni up`, this makes it run faster when we already checked if asdf is up to date, and if the asdf tool is up to date.
This does the same for the homebrew operation.
Closes https://github.com/XaF/omni/issues/229
> feat(homebrew operation): ✨ cache upgraded formula and cask for speed

- src/internal/cache/homebrew_operation.rs
- src/internal/cache/up_environments.rs
- src/internal/commands/builtin/up.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/golang.rs
- src/internal/config/up/homebrew.rs
- src/internal/config/up/mod.rs
- src/internal/config/up/nodejs.rs
- src/internal/config/up/options.rs
- src/internal/config/up/tool.rs
- src/internal/dynenv.rs
- website/contents/reference/02-builtin-commands/0250-up.md
This allows to make sure that any tool installed for a given repository is made available in the context of that repository. Prior to this change, it was expected that the homebrew bin path was loaded in the PATH environment variable by the user.
This slightly changes the update cache format to store the formulae bin paths. A new `--no-cache` parameter has been added to `omni up` in order to allow running `omni up` without taking the cache into account. This option only works for homebrew for now.
Closes https://github.com/XaF/omni/issues/256
> feat(homebrew operation): ✨ update PATH with installed formulae

- src/internal/config/up/homebrew.rs
With `brew` automatically falling back to cask when a formula is not found, this prevented omni to handle operations for casks in a different way than for formulae, for things that only work for formulae (e.g. `brew --prefix`). This changes that by passing an explicit `--formula` or `--cask` when performing actions.
BREAKING CHANGE: casks that did not have the `cask` explicit mention in `up:` operations will stop working. Simple fix is to prefix them by `cask:` if the cask name is provided inline (e.g. `- 1password-cli` should become `- cask: 1password-cli`.
> fix(homebrew operation)!: 🐛 require explicit `cask` mention

- src/internal/cache/homebrew_operation.rs
- src/internal/commands/builtin/up.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/golang.rs
- src/internal/config/up/homebrew.rs
- src/internal/config/up/nodejs.rs
- src/internal/config/up/options.rs
- src/internal/config/up/tool.rs
Since we are now using a cache to avoid checking that a given homebrew formula/cask is already installed or updated, or to resolve its homebrew path, let's simply clean things up when we uninstall a formula/cask so that on the next call it does not hit the cache.
Closes https://github.com/XaF/omni/issues/265
> fix(homebrew operation): 🐛 make sure to clean up the install cache

- src/internal/commands/builtin/up.rs
The `omni up` command was simply returning exit code `0` on error to set things up, instead of erroring out properly.
This is now fixed.
> fix(omni up): 🐛 return code should be 1 on error

- shell_integration/omni.fish.tmpl
Fixes https://github.com/XaF/omni/issues/128.
The `args` parsing code was sending the arguments as a single string, rather than as an array.
If you typed `omni config path <TAB>` then `["config path"]` was passed as args into `omni --complete` instead of the expected `["config", "path"]`.
> fix(shell integration): 🐛 arg parsing for fish auto-complete

- .omni.yaml
- src/internal/commands/base.rs
- src/internal/commands/fromconfig.rs
- src/internal/config/parser.rs
- website/contents/reference/01-configuration/0102-parameters/010250-commands.md
This is working similarly to the `dir` parameter of the custom operations when running `omni up`. This will execute the config command from the specified directory instead of from the directory of the configuration file.
For security reasons, the following constraints are applied:
- `dir` needs to be a path relative to the configuration file directory
- the joined path from the configuration file directory and `dir` must lead to a path contained inside the current directory
Closes https://github.com/XaF/omni/issues/245
> feat(config commands): ✨ add support for `dir` parameter

- src/internal/cache/up_environments.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/python.rs
- src/internal/config/up/tool.rs
https://github.com/XaF/omni/pull/277 introduced venv creation and was handling the deletion as part of the venv setup, which did not allow to handle multiple versions of python at the same time, except while using `auto`.
This fixes that by moving the data path cleanup to the cleanup process that handles removing unused versions at the end of an `omni up` or `omni down`.
This also means that it naturally handles the removal of the work directory data path as part of the `omni down` process.
Closes https://github.com/XaF/omni/issues/281
> feat(up tools): ✨ better cleanup for data paths

- Cargo.lock
- Cargo.toml
- src/internal/commands/utils.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/golang.rs
- src/internal/config/up/python.rs
- src/internal/config/up/utils.rs
- src/internal/dynenv.rs
This follows https://github.com/XaF/omni/pull/277 by making it so the golang up operation also gets an updated GOPATH for calls to `go install`.
> feat(up golang): ✨ Add GOPATH isolation for gcalls to go install

- src/internal/self_updater.rs
This was only showing that the update failed, this should show the error message.
> fix(self update): 🐛 show error message when failing to update

- src/internal/config/up/asdf_base.rs
- src/internal/config/up/golang.rs
- src/internal/config/up/python.rs
- src/internal/dynenv.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-python.md
This supports specifying one or more requirements files to be installed with `pip install -r` along with the python installation.
If the python installation is for multiple, isolated directories, each venv will get the `pip install -r` calls for each of the files.
If `auto` is passed to the `pip:` parameter, the default `requirements.txt` file will be looked for in each matching directory.
If the python version is `auto` and no `pip` parameter is specified, the `requirements.txt` file will be looked for in each matching directory.
Closes https://github.com/XaF/omni/issues/279
> feat(python operation): ✨ Add support for pip install

- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/up.rs
- src/internal/config/up/homebrew.rs
- src/internal/dynenv.rs
- src/internal/env.rs
- src/internal/git/updater.rs
- src/internal/workdir.rs
Packages can coexist with the worktree directory, and this could lead to development on a directory to override the package dependencies, or the other way around.
Packages should thus have a separate set of dependencies, making sure that dependencies are kept both for the package and worktree versions of a work directory, allowing them to coexist.
This handles that by changing the default id of work directories to be prefixed by `package#` for packages. The trust check is still handled through the simple, package-agnostic work directory id.
Closes https://github.com/XaF/omni/issues/278
> feat(packages): ✨ use a separate cache of dependencies

- src/internal/commands/base.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/fromconfig.rs
- src/internal/config/config_value.rs
- src/internal/config/loader.rs
- src/internal/config/mod.rs
- src/internal/config/parser.rs
This adds logic to automatically trust a configuration command if it is not setup in a work directory but in a broader-scope configuration file, such as the user home configuration file.
Closes https://github.com/XaF/omni/issues/246
> feat(config commands): ✨ trust the global-scoped configuration commands

- src/internal/commands/base.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/fromconfig.rs
- src/internal/commands/frommakefile.rs
- src/internal/commands/loader.rs
This creates aliases with the original name of a command read from either the configuration or a makefile, before any change was applied such as splitting on dashes or slashes. This allows to call a command with its original name.
Closes https://github.com/XaF/omni/issues/228
Closes https://github.com/XaF/omni/issues/45
> feat(commands): ✨ Add support for shadow aliases

- src/internal/commands/builtin/help.rs
This happened when having commands following the same general path but with steps auto-generated. The help was not merging those in the expected way.
> fix(help): 🐛 folded help was duplicating auto-generated commands

- src/internal/dynenv.rs
Go seems to consider an unset `GOPATH` the same as an empty-set `GOPATH`. This can be observed with:
```
$ GOPATH= && go env | grep GOPATH
GOPATH='/Users/xaf/go'
$ unset GOPATH && go env | grep GOPATH
GOPATH='/Users/xaf/go'
```
This changes the dynamic environment to behave the same way when setting the value of `GOMODCACHE`.
> fix(go dynenv): 🐛 consider empty GOPATH the same as unset GOPATH

- src/internal/dynenv.rs
List environment variables were set back to the empty string instead of being completely unset. This was an issue as empty strings-set environment variables might not have the same behavior as unset environment variables.
The issue manifested for the `GOPATH` variable since the recent changes to handle `GOPATH` as a list in the dynenv.
This fixes that by having a new list operation 'create', which is used when a list is being appended or prepended to for an environment variable that is currently unset.
> fix(dynenv): 🐛 unset properly list environment variables

- src/internal/config/up/options.rs
The homebrew operation cache was added but the writes were disabled, this enable the writes so that those operations can go faster when the cache is being used.
> fix(homebrew): 🐛 Enable cache write

- src/internal/dynenv.rs
This leads to a golang warning and should be avoided.
Fixes https://github.com/XaF/omni/issues/331
> fix(go dynenv): 🐛 do not set GOPATH to GOROOT

- .github/workflows/build-and-test-target.yaml
- .github/workflows/build.yaml
Tests for a specific build do not require builds of other versions to have finished. This creates a reusable workflow that takes care of building a specific version for a specific suffix, and running the relevant tests for that version if required.
Given that tests are generally run on faster builds (x86_64), this should accelerate the whole CI process as those will be able to be ran in parallel of other processes finishing building binaries.
> build: 👷 try and make builds a bit more parallel

- src/internal/commands/base.rs
- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/builtin/hook/base.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/commands/builtin/hook/uuid.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/frompath.rs
- src/internal/commands/loader.rs
- src/main.rs
Autocompletion in special cases where we had a subcommand was not completing for the parent command unless it was clear that we are not in the path of the subcommand.
For instance, adding an `omni cd blah` command was leading `omni cd <tab>` to always autocomplete by `blah`, since it would find the subcommand.
This makes it so, as long as we are not sure we are in the subcommand path, the parent command gets a chance to autocomplete too. This is done by calling the autocompletion on the parent command if found that we are in the process of autocompleting "one element after" the parent command.
Closes https://github.com/XaF/omni/issues/342
> feat(autocompletion): ✨ consider parent commands

- src/internal/cache/up_environments.rs
- src/internal/commands/builtin/up.rs
- src/internal/config/loader.rs
- src/internal/config/parser.rs
- src/internal/config/up/utils.rs
- src/internal/dynenv.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up_command.md
This allows users to know when the current work directory has an updated `up` configuration since `omni up` was last run, or has it available but `omni up` was never run yet.
The notifications will come as the prompt will print, the same way the dynamic environment update notifications appear, and use the configuration file(s) modification times but also a hash of the parameters that are pertinent for the up configuration, such that changing any other parameters in the configuration will not trigger a notification. The only parameters considered at this time are `up`,
`suggest_config` and `suggest_clone`.
This also comes with two configuration options to be able to disable any of those messages if desired:
- `notify_workdir_config_updated` to enable/disable notifications when `omni up` …
> feat(dynenv): ✨ show message when 'omni up' should be run

- src/internal/commands/builtin/clone.rs
- src/internal/config/parser.rs
- website/contents/reference/01-configuration/0102-parameters/010250-clone.md
This adds a configuration option on whether or not to automatically run `omni up` upon running `omni clone` on a repository. Defaults to `true`.
Closes https://github.com/XaF/omni/issues/200
> feat(clone): ✨ Add configuration option for `auto_up`

- src/internal/cache/up_environments.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/utils.rs
- src/internal/config/config_value.rs
- src/internal/config/loader.rs
- src/internal/config/parser.rs
- src/internal/dynenv.rs
- website/contents/reference/01-configuration/0102-parameters/0102-overview.md
- website/contents/reference/01-configuration/0102-parameters/010250-env.md
The `env` parameter was doing basic environment variable assignment, and did not take advantage of the whole capabilities of the dynamic environment. This changes that by adding more flexibility and support for also unsetting variables, but also list operations (append, prepend, remove from list).
This also supports handling paths by setting a `type: path` for environment variables. This allows for setting variables such as PYTHONPATH and equivalent.
Closes https://github.com/XaF/omni/issues/358
> feat(env): ✨ better handling of `up` environment variables

- src/internal/config/bootstrap.rs
- src/internal/config/loader.rs
- src/internal/config/parser.rs
This makes sure that after a user fills their configuration, it is immediately used by whatever omni command is being ran.
Fixes https://github.com/XaF/omni/issues/363
> fix(bootstrap): 🐛 flush config

- src/internal/commands/builtin/status.rs
- src/internal/config/parser.rs
- src/internal/git/org.rs
Fast search was not getting repositories in the default work tree if no org was defined.
This fixes that by adding a default organization which is not trusted, and does not contain any parameter, but allows to default operations for repositories specifying a full repo URL.
> fix(cd): 🐛 fast search now works without org set

- src/internal/commands/builtin/help.rs
- src/internal/user_interface/colors.rs
- src/internal/user_interface/print.rs
There was a bug where the colors in help messages from commands, short and long, were still showing when colors were disabled. This fixes that by stripping the colors from those messages when colors are disabled.
> fix(help): 🐛 colors are now stripped when disabled

- tests/test_omni_help.bats
Old bash versions have issues with single quotes (') in an heredocs
used for a variable assignment. This does not cause issues when using
the heredocs by itself.
To fix this issues, this replaces the `cat` calls to `read` calls.
> tests(bats): fix heredocs for old bash versions

- src/internal/cache/up_environments.rs
- src/internal/config/parser/env.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/golang.rs
- src/internal/config/up/mod.rs
- src/internal/config/up/nix.rs
- src/internal/config/up/tool.rs
- src/internal/dynenv.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-homebrew.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-nix.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-self.md
This adds support for the nix operation to install dependencies.
This creates a profile with the required packages (or from a specified nix file) and symlink its derivation into the gcroots to prevent nix garbage collection to kick-in for required packages.
Closes https://github.com/XaF/omni/issues/414
> feat(nix): ✨ add nix up operation

- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/bundler.rs
- src/internal/config/up/custom.rs
- src/internal/config/up/golang.rs
- src/internal/config/up/homebrew.rs
- src/internal/config/up/nix.rs
- src/internal/config/up/nodejs.rs
- src/internal/config/up/python.rs
- src/internal/config/up/tool.rs
- src/internal/config/up/utils.rs
- src/internal/dynenv.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-and.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-or.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-self.md
Some of the tooling installed through `asdf` requires dependencies to already be installed on the system. Those dependencies are stable and known in advance, as long as one of the known package managers that omni supports is available on the system.
This adds support so that when installing tools backed by `asdf`, the right dependencies will be setup on the system using either `brew` or `nix`. This should be extended in the future as support for `apt` and `dnf` is added back.
This also introduces new `or` and `and` operations for the `up` configuration, where `or` allows to indicate that one of the listed operations must succeed (`or` is marked unavailable and gracefully skipped if all underneath operations are unavailable), and will handle operations in the order they are defined, …
> feat(up): ✨ add dependencies handling and 'or' and 'and' operations

- .github/workflows/tests.yaml
- src/internal/commands/builtin/cd.rs
- website/contents/reference/02-builtin-commands/0250-cd.md
This adds support for `omni cd ...` to change directory to the root of the current work directory. This simplifies intra-project navigation by adding a handy shortcut.
Closes https://github.com/XaF/omni/issues/424
> feat(cd): ✨ special path '...' now represents the root of current work directory

- src/internal/config/loader.rs
- src/internal/config/parser/omniconfig.rs
- website/contents/reference/01-configuration/0101-files.md
This adds support for configuration files to be loaded before (pre) and after (post) the user configuration. These are considered global level but can allow to pre-fill default values to the configuration that the user can override (e.g. using `pre`) or to override values after the user-level configuration (e.g. using `post`).
This can also be used to set a default trusted organization for instance, which would always exist no matter what `org` the user configures:
```yaml
org__toappend:
- handle: git@github.com:XaF
trusted: true
```
Closes https://github.com/XaF/omni/issues/212
> feat(config): ✨ Add system-level configuration files

- src/internal/config/parser/omniconfig.rs
We now support a hash of the `up` configuration to indicate to the user when a new call to `omni up` should be performed. This now also takes into account the use of the `env` parameter, as it is also being setup in the dynamic environment and thus requires a refresh when updated.
Fixes https://github.com/XaF/omni/issues/397
> fix(up hash): 🐛 detect when `env` parameter has changed

- src/internal/cache/handler.rs
- src/internal/config/loader.rs
- src/internal/self_updater.rs
This is required by rust 1.77's clippy rules.
> fix: 🐛 Add truncate policy when opening files

- src/internal/cache/up_environments.rs
- src/internal/config/parser/env.rs
The up environment cache deserialization for environment variables had a bug since we didn't specify the default value for the operation type if not specified, while at the same time skipping serialization if the value was the default `set` value.
This fixes that by adding the `default` marker so serde knows to deserialize into the default value if none specified.
> fix(up env cache): 🐛 add default deserialization

- src/internal/commands/builtin/help.rs
- src/internal/user_interface/print.rs
- tests/helpers/utils.bash
- tests/test_omni_help.bats
This handles lower resolutions of terminal by splitting the command name over multiple lines if needed. It also adds an error message for very low terminal resolutions.
Fixes https://github.com/XaF/omni/issues/462
> fix(help): 🐛 handle lower terminal width properly

- src/internal/commands/builtin/help.rs
- src/internal/config/parser/up_command.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/tool.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-any.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-self.md
- website/contents/reference/01-configuration/0102-parameters/010250-up_command.md
This operation works like `or` but handles user preference where `or` only considers operation order. If any tools are defined in `preferred_tools`, these would be considered in priority before defaulting to the rest of the available operations.
This allows for a better handling of dependencies by using the tools that the user favor, even if other tooling is available in the system.
Closes https://github.com/XaF/omni/issues/464
> feat(up): ✨ add the `any` operation and `preferred_tools` config

- .github/workflows/tests.yaml
- src/internal/config/up/utils.rs
- src/internal/user_interface/mod.rs
- src/internal/user_interface/print.rs
Previous approach was not keeping track of the length of lines, which in turn led to newlines being printed even though it was not required. Now we keep track of the length of the last line printed in a spinner, and only add a line return if it went over the expected line length.
> fix(spinners): 🐛 new lines are now ensured properly after a spinner

- src/internal/config/up/asdf_base.rs
In 0.0.22, the improved data path cleanup unfortunately didn't follow the auto-discovered versions to know which data paths to keep, leading to cleaning up needed directories.
This fixes that by bubbling down the data paths of all installed versions in all directories.
> fix(cleanup): 🐛 data path cleanup won't delete auto versions

- src/internal/cache/github_release.rs
- src/internal/cache/utils.rs
- src/internal/config/up/github_release.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-github-release.md
Initial approach for `github-release` was to only support archives of .tar.gz or .zip format. This adds support for files without extension that could be a binary file. Note however that this will not do any validation when it's the case.
> feat(github-release): ✨ support binary downloading

- src/internal/commands/base.rs
- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/config/mod.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/config/reshim.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/builtin/hook/base.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/commands/builtin/hook/uuid.rs
- src/internal/commands/builtin/mod.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/loader.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/utils/directory.rs
- src/internal/config/up/utils/mod.rs
- src/internal/config/up/utils/shims.rs
- src/internal/dynenv.rs
- src/internal/env.rs
- src/main.rs
- website/contents/reference/02-builtin-commands/02-overview.md
- website/contents/reference/02-builtin-commands/0250-config/0250-reshim.md
- website/contents/reference/02-builtin-commands/0250-up.md
Some tools cannot work directly with the dynamic environment, such as some IDEs. Adding a shims directory that dynamically gets updated on `omni up` allows for a better handling of those IDEs, as they can just fetch the binary from the PATH.
The shims script will simply load omni's environment for the work directory they are being called from, and call the corresponding binary in the PATH. If that PATH does not provide that binary, it will lead to an error. Otherwise, it will return the first matching version of the corresponding binary.
This also adds `omni config reshim` command to update all shims if necessary. This shouldn't be necessary most of the time though, as shims are being regenerated automatically on `omni up`.
Closes https://github.com/XaF/omni/issues/492
> feat(shims): ✨ add a shims directory with all dynamic binaries

- src/internal/cache/repositories.rs
- src/internal/commands/base.rs
- src/internal/commands/builtin/config/mod.rs
- src/internal/commands/builtin/config/trust.rs
- src/internal/commands/builtin/mod.rs
- src/internal/commands/loader.rs
- src/internal/workdir.rs
- website/contents/reference/02-builtin-commands/02-overview.md
- website/contents/reference/02-builtin-commands/0250-config/0250-trust.md
- website/contents/reference/02-builtin-commands/0250-config/0250-untrust.md
This introduces the new `omni config trust` and `omni config untrust` commands to manage a repository trust in the cache.
This is useful to be proactive about trusting specific repositores or removing the trust of a repository trusted by mistake.
Closes https://github.com/XaF/omni/issues/496 and https://github.com/XaF/omni/issues/487
> feat(config trust): ✨ command to manage workdir trust

- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/env.rs
- templates/shell_integration.bash.tmpl
- templates/shell_integration.fish.tmpl
- templates/shell_integration.zsh.tmpl
- website/contents/reference/02-builtin-commands/0250-hook.md
This allows to call `omni hook init --shims` to only prepend the shims to the `PATH`. This also supports prepending the shims to the environment automatically for non-interactive shells.
Closes https://github.com/XaF/omni/issues/498
> feat(hook init): ✨ handle shims

- src/internal/config/up/base.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/mod.rs
- src/internal/config/up/tool.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-github-release.md
GitHub release operation required to add an entry for each release, which made it verbose both to write the configuration and during `omni up`. This fixes that by allowing to specify multiple versions, either as a list or as a map of repository => repository config.
When used with multiple versions, this will show as a single entry that will summarize the installed releases at the end.
> feat(github release): ✨ add more compact configuration handling

- src/internal/self_updater.rs
If people are disabling homebrew auto-updates, when running `brew upgrade xaf/omni/omni` there will be no new version to upgrade to, leaving omni in its previous version.
This fixes that by calling `git pull` in the repository of omni's tap first, so that we ensure the tap is up-to-date before calling upgrade.
This also disables other auto-updates of homebrew during the omni self-update.
Closes https://github.com/XaF/omni/issues/495
> fix(self update): 🐛 force-refresh tap before upgrading omni

- src/internal/cache/github_release.rs
- src/internal/config/up/error.rs
- src/internal/config/up/github_release.rs
Previously, the cache was kept for the duration even if no release matched the requirements. With that change, if the cache was used and no release matches the requirements, the cache will be refreshed and the releases evaluated a second time.
This allows to satisfy bound requirements (e.g. specific version number) even if the change to the requirement is recent and the cache has been refreshed recently for the user.
Closes https://github.com/XaF/omni/issues/486
> feat(github release): ✨ try refreshing releases cache if none match

- src/internal/cache/asdf_operation.rs
- src/internal/cache/up_environments.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/tool.rs
- src/internal/config/up/utils/print_progress_handler.rs
- src/internal/dynenv.rs
A large number of `asdf` tools are available that omni can take advantage of right away, but this was not available as requiring specific tool definition to work.
This changes that by changing the default behavior when a tool is unknown, and considering it's an asdf plugin by default.
This also adds support for the `url` parameter to any asdf tool, which will override the repository used for that tool. If this does not correspond to the default tool URL, it will keep the tool installation separate from one that wouldn't provide an `url` or would provide a different one.
Closes https://github.com/XaF/omni/issues/494
> feat(asdf): ✨ add suppport for arbitrary asdf tools

- src/internal/config/template.rs
- website/contents/reference/01-configuration/0104-templates.md
This allows to access environment variables when using templates, in the shape of a key-value map.
Closes https://github.com/XaF/omni/issues/493
> feat(template): ✨ add `env` map in the context

- src/internal/config/up/asdf_base.rs
- src/internal/config/up/golang.rs
- src/internal/config/up/python.rs
Since when passing a URL we get a different tool name, suffixed with a hash, this required adding support for that when calling the detect func (to always only use the real tool name) and the post install func (so it can decide which one it uses depending on what it wants to do).
> fix(asdf): 🐛 post install and detect func use the real tool name

- src/internal/config/up/asdf_base.rs
`vendor` directories were not ignored when using `auto` for detecting automatically the right version(s) to install for tools, leading to some unneeded versions to be installed and setup in the environment.
This changes that by ignoring any `vendor` directory that is not _directly_ listed as a directory for which to detect versions from.
Closes https://github.com/XaF/omni/issues/425
> fix(up auto): 🐛 ignore vendor directories

- src/internal/config/up/github_release.rs
This allows to handle downloading releases from private repositories, since they require a token to get access, and `gh` can provide that token, both for the regular `github.com` host, but also for GitHub enterprise hosts.
Closes https://github.com/XaF/omni/issues/478
> feat(github release): ✨ read github auth token from `gh`

- src/internal/config/up/nix.rs
- tests/fixtures/bin/generic.sh
- tests/test_omni_up_python.bats
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-nix.md
Nix flakes are slightly different than nix profiles and require special handling. This adds omni support for nix flakes by behaving differently when using the `flake.nix` file, which can also be automatically-detected in a work directory.
Closes https://github.com/XaF/omni/issues/466
> feat(nix): ✨ handle flakes

- src/internal/config/up/asdf_base.rs
- src/internal/config/up/homebrew.rs
Homebrew supports auto-tapping formulas using the long format `tap-owner/tap-name/formula`, which will automatically tap the formula when calling `brew install`. However, this won't allow for omni to keep track of what's being tapped and what needs to be cleaned up.
To solve that problem, omni will now automatically extract the tap when using that format, so that taps can be automatically untapped when not used anymore (if omni triggered the initial tapping).
Closes https://github.com/XaF/omni/issues/516
> feat(homebrew): ✨ auto-extract taps from formulas

- .github/workflows/tests.yaml
- tests/test_omni_up_homebrew.bats
One of the `bats` tests failed, but the `check test results` step of the tests did not fail, which led to the code being merged. This should have blocked the merge until the tests passed.
This should fix that situation, as well as the broken test.
> build(status): 👷 fix check of test results

- src/internal/config/parser/path_repo_updates.rs
- src/internal/git/mod.rs
- src/internal/git/updater.rs
- src/main.rs
- website/contents/reference/01-configuration/0102-parameters/010250-path_repo_updates/010250-self.md
`omni` was automatically triggering a synchroneous update on command not found (if due) in order to make sure to run the command if available.
The new `path_repo_updates`/`on_command_not_found` option in the configuration can be set to either one of `true`, `false` or `ask`. If set to `ask`, which is the default, it will ask the user before running any sync update -- Note that answering 'no' will still trigger updates, but in the background. If set to `true`, sync updates will be triggered without any question. If set to `false`, no update will be triggered at all.
Closes https://github.com/XaF/omni/issues/482
> feat(update): ✨ ask before updating on command not found

- src/internal/cache/asdf_operation.rs
- src/internal/cache/github_release.rs
- src/internal/cache/homebrew_operation.rs
- src/internal/config/parser/cache/asdf.rs
- src/internal/config/parser/cache/github_release.rs
- src/internal/config/parser/cache/homebrew.rs
- src/internal/config/parser/cache/mod.rs
- src/internal/config/parser/cache/root.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/homebrew.rs
- src/internal/env.rs
- website/contents/reference/01-configuration/0102-parameters/010250-cache/010250-asdf.md
- website/contents/reference/01-configuration/0102-parameters/010250-cache/010250-github_release.md
- website/contents/reference/01-configuration/0102-parameters/010250-cache/010250-homebrew.md
- website/contents/reference/01-configuration/0102-parameters/010250-cache/010250-self.md
Resources cleanup is done as soon as a resource is not in use. However, when switching between branches, this might lead to a lot of resources being cleaned-up and reinstalled, etc.
This adds a grace period between a resource not being used anymore and it being cleaned up; it defaults to 1 week, but can be changed to `0` to restore previous behavior, or to any other discretionary period of time.
Individual configuration options are available depending on the resource type, so that they can each behave differently:
- `cache`/`asdf`/`cleanup_after` for the cleanup of asdf versions
- `cache`/`homebrew`/`cleanup_after` for the cleanup of homebrew taps and formulae
- `cache`/`github_release`/`cleanup_after` for the cleanup of GitHub releases
Closes https://github.com/XaF/omni/issues/435
> feat(cleanup): ✨ add delay before removing unused resources

- src/internal/config/up/github_release.rs
- src/internal/config/up/utils/mod.rs
- src/internal/config/up/utils/version.rs
If there is any error during download of a release, we now fallback to an installed version matching the criteria. This is similar to what was done for `asdf` operations, but applied to GitHub releases.
For instance, if I am installing version `2`, and the latest version fitting with `2` is `2.0.9` and I fail downloading it, if `2.0.8` is already installed, since it fits with my requirement of `2`, ommi will automatically fallback to that version.
This allows to avoid losing a working dev environment in case the internet connectivity is having issues, for instance.
Closes https://github.com/XaF/omni/issues/526
> feat(github release): ✨ fallback to installed version if download error

- Cargo.lock
- Cargo.toml
- src/internal/env.rs
Update from https://github.com/XaF/omni/pull/532 that does not work since breaking changes in the `petname` crate in 2.0.0.
> chore(deps): bump petname from 1.1.3 to 2.0.1

- Cargo.lock
- Cargo.toml
- src/internal/cache/github_release.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/utils/directory.rs
- src/internal/config/up/utils/up_progress_handler.rs
- src/internal/env.rs
The GitHub release operation needs testing directly in rust to be able to mock HTTP queries. This adds a number of tests around the parsing of the parameters but also the queries being done.
> test(github release): 🧪 add tests

- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/config/up/utils/shims.rs
- src/internal/dynenv.rs
- templates/shell_integration.bash.tmpl
- templates/shell_integration.fish.tmpl
- templates/shell_integration.zsh.tmpl
This allows to make things work for any non-interactive shell, which would not load the dynamic environment, and still have the shims loaded.
> refactor(shims): ♻️  shims are now always loaded but removed by dynenv

- src/internal/config/parser/env.rs
The `env` parameters of type `path` were keeping the configuration file in the resolves relative path, which was obviously not working and there were no directory of the name of the config file.
This is fixed by resolving the parent of the config file path, which is thus the directory in which the config file is, and applying the relative path resolution from there.
Fixes https://github.com/XaF/omni/issues/564
> fix: 🐛 `env` config parameter of type `path` now resolves properly

- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/config/parser/org.rs
- src/internal/git/mod.rs
- src/internal/git/org.rs
- src/internal/git/utils.rs
- website/contents/reference/01-configuration/0102-parameters/010250-org.md
`repo_path_format` is used to define the format of the path to repositories inside a worktree. Until now, this was only available as a global configuration option, while it was possible to define a different worktree per organization.
This fixes that by adding a `repo_path_format` in the per-org configuration, which will apply to the specific organization only.
Closes https://github.com/XaF/omni/issues/561
> feat(repo_path_format): ✨ can be configured per organization

- src/internal/config/up/nodejs.rs
When using `auto`, omni will also consider the `.nvmrc` files to install the correct versions.
Closes https://github.com/XaF/omni/issues/507
> feat(node): ✨ support reading version from .nvmrc

- src/internal/config/parser/askpass.rs
- src/internal/config/up/utils/askpass.rs
- templates/askpass.sh.tmpl
- website/contents/reference/01-configuration/0102-parameters/010250-askpass.md
This allows to disable the GUI by setting the configuration to `false`. In which case, if the shell is not interactive when a password is requested, the askpass command will simply fail, leading to the calling command failure.
Closes https://github.com/XaF/omni/issues/581
> feat(askpass): add `enable_gui` configuration

- src/internal/commands/frompath.rs
- src/internal/commands/loader.rs
- src/internal/config/parser/path.rs
- src/main.rs
- website/contents/reference/01-configuration/0103-environment.md
This new flag makes the current omni process lookup for commands in the current directory first. It also follows any `suggest_config` that exists in the repository configuration, even if those suggestions have not been applied to the user configuration.
Note that this flag does not get inherited when `omni` is then called from a command called through `omni --local`. The absence of propagation is done on purpose so that `omni --local` is _required_ for prioritizing local commands over global ones. We do however set a `OMNI_LOCAL_LOOKUP` environment variable that can be consumed by subcommands if needed, but that is ignored by `omni` itself.
Closes https://github.com/XaF/omni/issues/577
> feat: Add `--local` global flag

- src/internal/cache/homebrew_operation.rs
- src/internal/config/parser/cache/homebrew.rs
- src/internal/config/up/homebrew.rs
Up until now, omni was depending on homebrew to update taps before calling `brew update` on a specific formula. This however does not work when homebrew defaults to disabling updating of all taps automatically, leading to versions never being updated in such case.
This changes this by using `git pull` in the repository where the tap is checked out before calling any `brew update`, which leads to making sure these are updated. Moreover, it adds environment variables to prevent calls to `brew update` to update _all_ the taps available.
Closes https://github.com/XaF/omni/issues/611
> feat(homebrew): ✨ update taps using git

- Cargo.lock
- Cargo.toml
- src/internal/commands/base.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/frompath.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/nodejs.rs
- src/internal/config/up/options.rs
- src/internal/config/up/utils/mod.rs
- src/internal/config/up/utils/up_progress_handler.rs
- src/internal/env.rs
- src/internal/errors.rs
- src/internal/git/org.rs
- src/internal/git/updater.rs
- src/internal/mod.rs
- src/main.rs
- website/contents/reference/03-custom-commands/0302-path/030201-metadata-headers.md
Until now, `omni up` could be run multiple times in parallel, this
also meant that if a repository is already being updated in the
background, it would be updated a second time synchronously by calling
`omni up`. This changes that by allowing any new `omni up` to attach
to a currently-running `omni up` operation.
This effectively allows to move all updates to be background-only
updates, as it is now possible for an up operation to run in the
background, but to be attached to the current process if necessary.
Closes https://github.com/XaF/omni/issues/686
> feat(up): ✨ synchronize 'omni up' operations

- src/internal/config/parser/github.rs
- src/internal/config/parser/mod.rs
- src/internal/config/parser/omniconfig.rs
- src/internal/config/up/github_release.rs
- website/contents/reference/01-configuration/0102-parameters/0102-overview.md
- website/contents/reference/01-configuration/0102-parameters/010250-github.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-github-release.md
The auth token was previously only pulled from the `gh` tool, by calls to `gh auth token` which weren't configurable.
This changes that by allowing to configure things at different levels. First, it can be configured in the user and/or system configuration by using the new `github:` configuration section:
```yaml
github:
auth:
token: <token value>
```
This can also be a list, with matching for the repository and/or the used API URL, e.g.:
```yaml
github:
auth:
- repo:
glob: XaF/*
skip: true  # Skip authentication
- gh  # Use `gh` by default
```
Note that if going through the list, no match is found, it will default to use the `gh` command line. To skip all authentication by default, you can use `- skip` as the last value of the list for instance (without `repo` or `api_url` filter. …
> feat(github release): ✨ configurable github auth token

- src/internal/cache/github_release.rs
- src/internal/self_updater.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-github-release.md
If using an ARM Mac with Rosetta installed, omni will now default to download GitHub releases that are compatible with x86_64 if it fails to find an ARM release. This will ensure extended compatibility for systems that support those.
Closes https://github.com/XaF/omni/issues/647
> feat(github release): ✨ suppport extended architectures with rosetta

- website/contents/tutorials/04-ide-integration.md
This updates the Emacs configuration instructions to trim spurious newlines from Omni's output.
Tested on three differently configured emacs installs :P
> Update Emacs configuration instructions

- src/internal/config/up/asdf_base.rs
- tests/test_omni_up_python.bats
I encountered the following problem today when omni attempted to install python in the background:
```
[1/5] - python (3): deps: evaluating file '/nix/store/93haqkb7bl8l90vpfqgkygrd5l13gafm-source/pkgs/by-name/gd/gdbm/package.nix'
[1/5] - python (3): deps: error:
[1/5] - python (3): deps:        … while calling the 'derivationStrict' builtin
[1/5] - python (3): deps:          at <nix/derivation-internal.nix>:34:12:
[1/5] - python (3): deps:            33|
[1/5] - python (3): deps:            34|   strict = derivationStrict drvAttrs;
[1/5] - python (3): deps:              |            ^
[1/5] - python (3): deps:            35|
[1/5] - python (3): deps:        … while evaluating derivation 'nix-shell'
[1/5] - python (3): deps:          whose name attribute is located at …
```
> fix(python): replace lzma with xz when using nix

- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/config/trust.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/builtin/hook/base.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/frompath.rs
- src/internal/commands/void.rs
- src/internal/config/parser/command_definition.rs
- src/internal/config/parser/mod.rs
Previously, we had a separation between the primary name and aliases, and we merged the information together before extracting the expected main long name and main short name. This fixes that by merging everything into a single 'names' list, and applying the same extraction logic but avoiding the initial merging of the lists.
This also applies the splitting logic when defining a parameter from the .omni.yaml file or the metadata yaml file, allowing to use the same syntax as the `# opt` and `# arg` metadata headers.
> refactor(SyntaxOptArg): takes a single list of names

- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/path.rs
- src/internal/config/parser/env.rs
- src/internal/config/parser/path.rs
- src/internal/git/updater.rs
Packages were not processing path environment variables properly. This change fixes that by extracting the package path to handle the environment variable properly.
> fix(env): path environment variables work for packages

- src/internal/env.rs
This was causing issues when the `HOMEBREW_PREFIX` environment variable is not set, since the `brew --prefix` output ends with a line return. Trimming solves the problem.
> fix(self update): trim homebrew prefix from binary

- src/internal/env.rs
- src/internal/git/updater.rs
- src/internal/self_updater.rs
For cases where omni was installed in a location where sudo access is not available, this will print a message requesting `sudo` instead of failing the update.
> fix(self update): handle cases where sudo is required

- src/internal/commands/builtin/hook/init.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/frompath.rs
- src/internal/config/parser/command_definition.rs
- tests/fixtures/omni/help-cd.txt
- tests/fixtures/omni/help-clone.txt
- tests/fixtures/omni/help-config-path-switch.txt
- tests/fixtures/omni/help-config-path.txt
- tests/fixtures/omni/help-config-trust.txt
- tests/fixtures/omni/help-config-untrust.txt
- tests/fixtures/omni/help-config.txt
- tests/fixtures/omni/help-help.txt
- tests/fixtures/omni/help-hook-env.txt
- tests/fixtures/omni/help-hook-init.txt
- tests/fixtures/omni/help-hook.txt
- tests/fixtures/omni/help-scope.txt
- tests/fixtures/omni/help-tidy.txt
- tests/test_omni_help.bats
- website/contents/reference/01-configuration/0102-parameters/010250-commands.md
This helps with a nicer help experience when using omni's argument parser, as parameters taking multiple values can use the placeholders to give more information about the expected values in the help message.
> feat(`argparser`): the `placeholders` can now allow multiple values

- src/internal/cache/github_release.rs
- src/internal/config/up/github_release.rs
- src/internal/self_updater.rs
This adds support for 'universal' binaries as a second-level priority when finding assets in a github release. This will match words such as `universal`, `all` or `any` in those instances.
The initial filtering of the assets also uses regex instead of simple string 'contains' checking.
Fixes https://github.com/XaF/omni/issues/779
> feat(`github-release`): improvements to arch pattern matching

- .github/workflows/build-and-test-target.yaml
- Cargo.lock
- Cargo.toml
- src/internal/cache/up_environments.rs
- src/internal/config/up/custom.rs
- src/internal/config/up/tool.rs
- src/internal/config/up/utils/askpass.rs
- src/internal/config/up/utils/fifo_handler.rs
- src/internal/config/up/utils/listener_manager.rs
- src/internal/config/up/utils/mod.rs
- src/internal/config/up/utils/progress_handler.rs
- src/internal/config/up/utils/run_config.rs
- tests/helpers/utils.bash
- tests/test_omni_up_custom.bats
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-custom.md
The `custom` operations of `omni up` now allow for adding environment variables in the dynamic environment through the special `$OMNI_ENV` environment variable provided during the `custom` operations.
This variable works similarly to `$GITHUB_ENV` in GitHub actions for instance. It supports the basic environment setting format:
- `unset VAR` to unset a variable
- `VAR=value` to set a variable to the value `value`
- `VAR<<EOF` followed by any number of lines, followed by a delimiter (like `EOF`) to set a multiline environment variable using heredoc formatting (`VAR<<-EOF` also works to remove all indentation, and `VAR<<~EOF` to remove the minimum indentation)
It does also support extended operations. These are safer to use for the dynamic environment provided by omni, as they are applied …
> feat(`custom`): add support for adding environment variables

- src/internal/config/up/utils/directory.rs
`cleanup_path` would throw an error when attempting to clean up symlinks to the nix store.
It shouldn't, so let's clean them up!
> fix(cleanup): correctly delete symlinks

- src/internal/cache/cargo_install.rs
- src/internal/cache/database/sql/cargo_install_operation_add.sql
- src/internal/cache/database/sql/cargo_install_operation_add_required_by.sql
- src/internal/cache/database/sql/cargo_install_operation_add_versions.sql
- src/internal/cache/database/sql/cargo_install_operation_cleanup.sql
- src/internal/cache/database/sql/cargo_install_operation_get_versions.sql
- src/internal/cache/database/sql/cargo_install_operation_list_installed.sql
- src/internal/cache/database/sql/create_tables.sql
- src/internal/cache/mod.rs
- src/internal/config/parser/cache/cargo_install.rs
- src/internal/config/parser/cache/mod.rs
- src/internal/config/parser/cache/root.rs
- src/internal/config/up/asdf_base.rs
- src/internal/config/up/base.rs
- src/internal/config/up/cargo_install.rs
- src/internal/config/up/go_install.rs
- src/internal/config/up/mod.rs
- src/internal/config/up/tool.rs
- src/internal/config/up/utils/askpass.rs
- src/internal/config/up/utils/up_progress_handler.rs
- src/internal/config/up/utils/void_progress_handler.rs
- src/internal/testutils.rs
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-cargo-install.md
- website/contents/reference/01-configuration/0102-parameters/010250-up/010250-self.md
- website/contents/reference/03-custom-commands/0302-path/030203-argument-parser.md
- website/docusaurus.config.js
This introduces a new `cargo-install` operation for `up`, which installs a tool using `cargo install`. This supports finding available versions through the crates.io API, or using exactly the specified version without lookup. This also takes care of loading a `rust` version to call the `cargo` commands with.
Closes https://github.com/XaF/omni/issues/798
> feat(`up`): ✨ add `cargo-install` operation

- src/internal/config/parser/command_definition.rs
This is a well-known format that was not supported so far. This fixes add by supporting either spaces or `=` when separating the argument from the placeholder.
Closes https://github.com/XaF/omni/issues/794
> feat(`argparser`): support using `--arg=PLACEHOLDER`

- Cargo.toml
This should allow `cargo binstall` to locate the pre-built binaries from the github releases.
> chore(`binstall`): add metadata for binstall

- Cargo.lock
- Cargo.toml
[`serde_yaml`](https://docs.rs/serde_yaml/latest/serde_yaml/) got deprecated, [`serde_yml`](https://docs.rs/crate/serde_yml/latest) is a drop-in replacement fork from the original.
> chore(`serde_yaml`): replace deprecated dependency

- src/internal/config/up/cargo_install.rs
- src/internal/config/up/go_install.rs
- tests/test_omni_up_go_install.bats
The new `cargo-install` and `go-install` operations support specifying versions using the `@` symbol, like when using the tool with either `cargo install <crate>[@<version>]` or `go install <path>[@<version>]`, but this was interpreted the same was as a weak version specification.
This changes that by considering that `@`-versions are an exact specification.
> chore(@-version): handle @-version as exact matching

- src/internal/cache/utils.rs
- src/internal/commands/builtin/help.rs
- src/internal/config/up/utils/progress_handler.rs
- src/internal/user_interface/print.rs
- tests/fixtures/omni/help-cd-json.txt
- tests/fixtures/omni/help-config-bootstrap-json.txt
- tests/fixtures/omni/help-config-json.txt
- tests/fixtures/omni/help-help.txt
- tests/fixtures/omni/help-json.txt
- tests/fixtures/omni/help-unfold-json.txt
- tests/fixtures/omni/help-up-json.txt
- tests/test_omni_help.bats
This allows to get the help messages in a programmatically parseable way, which can open the door for generating documentation from the help output of omni.
Closes https://github.com/XaF/omni/issues/809
> feat(`help`): ✨ add `--output` flag which can take `plain` or `json`

- src/internal/config/parser/up_command.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/mise.rs
- tests/fixtures/omni/status-config.txt
- website/contents/reference/01-configuration/0102-parameters/010250-up_command.md
By default, `omni` will install and update `mise` regularly to keep using the latest version. This parameter however will allow to pin `mise` to a given version. The version can be defined the same way as any version can be defined when using github releases.
> feat(`up`): allow to configure `mise` version

- .github/workflows/build-and-test-target.yaml
This introduces the use of the cache which is wiping the cargo directory and leading to failures in building binaries. This is fixed by disabling the cache for this action on top of reordering operations, since we already are handling the cache ourselves anyway.
> build(`cross`): 👷 fix for `actions-rust-cross`'s v1

- src/internal/config/parser/up_command.rs
- src/internal/config/up/bundler.rs
- src/internal/config/up/cargo_install.rs
- src/internal/config/up/custom.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/go_install.rs
- src/internal/config/up/homebrew.rs
- src/internal/config/up/mise.rs
- src/internal/config/up/nix.rs
- tests/helpers/mise.bash
- tests/test_omni_up_custom.bats
- tests/test_omni_up_go_install.bats
- tests/test_omni_up_python.bats
- website/contents/reference/01-configuration/0102-parameters/010250-up_command.md
When using many sources to install tools for an environment, there can be supply chain concerns. This aims at addressing those by adding configuration to allow/deny specific operations for the `up` command, as well as specific sources for those operations. This also allows to allow/deny specific backends for mise, including a special "custom" backend for user-provided or system-provided urls.
A special parameter also allows to set default URLs for specific tools, allowing to override the plugin to be used by default for a tool.
Closes https://github.com/XaF/omni/issues/600
> feat(`up`): ✨ add supply-chain checks

- src/internal/config/up/mise.rs
When `asdf` was used, we added the `asdf` binary in the `PATH` as some plugins depend on being able to call `asdf`. For `mise`, we initially removed that believing that the `mise` binary didn't depend on plugins being able to call back `mise`, or that for some reason `mise` would add itself to the `PATH` when operating on `asdf` plugins. This does not seem to be the case however, and thus this adds the `mise/bin/` directory to the `PATH`, which restore the behavior we had with `asdf`.
> fix(`mise`): 🐛 add the `mise` binary in the `PATH` for `mise` commands

- src/internal/config/up/cargo_install.rs
- src/internal/config/up/go_install.rs
The `--no-cache` option, when used with `cargo-install` and `go-install` was failing with issues to replace binary files. This was caused by the `bin` directory already existing.
On top of that, the `cargo-install` action was failing because of replacement of the `rust` install backed by `mise`, since the right environment variables were not put in place. This is fixed by adding those environment variables.
Related to https://github.com/XaF/omni/issues/864
> fix(`cargo-install` and `go-install`): `--no-cache` now works

- src/internal/cache/github_release.rs
- src/internal/config/up/github_release.rs
Following https://github.com/XaF/omni/pull/863, we now can end-up getting a lot of pages of releases each time we refresh the list of available releases.
Since GitHub new releases are added in the first pages, we can use the existing cached releases (unless called with `--no-cache`) to simply add new releases and thus only query the first few pages until we get to releases we already know about.
This will reduce the usage of the API to the bare minimum necessary to be aware of new releases.
> feat(`github-releases`): ✨ optimize version fetching

- .omni.yaml
- src/internal/commands/base.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/config/parser/command_definition.rs
- tests/fixtures/omni/help-tidy.txt
Closes https://github.com/XaF/omni/issues/853
> fix(`argparser`): `last` argument is now shown after `--` in the help

- src/internal/commands/base.rs
- src/internal/commands/builtin/config/check.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/fromconfig.rs
- src/internal/commands/frompath.rs
- src/internal/config/parser/check.rs
- src/internal/config/parser/command_definition.rs
- src/internal/config/parser/errors.rs
- src/internal/config/parser/github.rs
The tags will appear in the help of a command, and can be checked against using the `config check` command. The checks can be used to validate that a tag exists, or that it has a specific value, either matching exactly or against a pattern.
Closes https://github.com/XaF/omni/issues/858
> feat(`tags`): ✨ commands can now be tagged

- Cargo.lock
- Cargo.toml
- src/internal/commands/builtin/status.rs
- src/internal/env.rs
- src/internal/user_interface/colors.rs
The `is_terminal()` method is now part of the standard library since rust 1.70.0, so we can remove the dependency to the `is-terminal` crate.
> chore(`IsTerminal`): use the `std` trait `IsTerminal`

- src/internal/commands/builtin/up.rs
- src/internal/config/parser/up_command.rs
- src/internal/config/up/utils/up_progress_handler.rs
- src/internal/env.rs
- src/internal/errors.rs
- tests/fixtures/omni/status-config.txt
The `omni up` (and respectively `omni down`) command will try to attach to any running `omni up` or `omni down` command that is already running for the current work directory. However, in cases where there is a connectivity issue (e.g. computer going to sleep), it is possible for the `omni up` command to hang indefinitely (e.g. waiting for a network response).
When attaching to a running process, this will trigger a timeout after a few minutes if the process seems to be hanging, offering the user to kill the running process.
Closes https://github.com/XaF/omni/issues/877
> feat(`up`): ✨ timeout and offer to kill running `up` if hanging

- src/internal/config/up/mise.rs
Since the switch to associate an environment at the end of up, we depend on getting the version of the tool at the end to link required versions to the environment that required them.
When `auto` is used, if no version is detected, no version gets set in the list of resolved versions, which thus led to an error.
This fixes that issue by setting the versions to an empty list when running an operation with `auto` which did not detect any version to install.
Closes https://github.com/XaF/omni/issues/852
> fix(`auto`): do not return an error if no version detected

- src/internal/config/parser/up_command.rs
- src/internal/config/up/utils/up_progress_handler.rs
- src/internal/env.rs
- src/internal/errors.rs
- tests/fixtures/omni/status-config.txt
Previous commit added the query for same init when the process seems to be hanging, this adds a check of the file last modified time right as we read the init data, allowing to offer killing the running process if it has been hanging for longer than expected, no matter if the init contents is matching or not.
> feat(`up`): ✨ handle hanging process with mismatched init

- src/internal/commands/builtin/config/check.rs
- src/internal/config/parser/check.rs
- src/internal/config/utils.rs
- website/contents/reference/configuration/parameters/check.md
This improves the handling of the location of the patterns when passed
from configuration files or from the command line.
> fix(`config check`): 🐛 pattern locality 

- src/internal/config/up/utils/shims.rs
This was leading to errors if two shims have the same name with a different case, as rust is case sensitive, and if the file system is not, it will try creating two shims which will seem the same for the file system.
Closes https://github.com/XaF/omni/issues/891
> fix(`shims`): 🐛 handle case insensitive file systems

- src/internal/git/updater.rs
- src/internal/self_updater.rs
- src/main.rs
This will only trigger updating omni itself if a new version is available.
Closes https://github.com/XaF/omni/issues/897
> feat(`self-update`): add `omni --self-update` support

- src/internal/cache/github_release.rs
- src/internal/config/up/github_release.rs
- src/internal/utils/libc.rs
- src/internal/utils/mod.rs
- website/contents/reference/configuration/parameters/up/github-release.md
This replaces the `prefer_musl` flag by a detection, which makes more sense actually, since it would depend on the current system.
Partially reverts 24faed98d19a529196915b70ac51731c0eca8802
> fix(`github-release`): 🐛 detect the lib version needed (musl/libc)

- Cargo.lock
- Cargo.toml
- src/internal/cache/github_release.rs
- src/internal/config/up/github_release.rs
On top of the already-supported `.tar.gz` and `.zip` archives.
> feat(`github-release`): ✨ support extracting `.tar.xz` archives

- src/internal/cache/database/sql/upgrade_v2_to_v3.sql
- src/internal/cache/database/upgrade.rs
- src/internal/cache/github_release.rs
- src/internal/config/up/github_release.rs
GitHub requires to use the asset API URL in order to download resources from a private repository, as the browser URL does not support the `Bearer` token authentication. This makes this work.
> fix(`github-release`): 🐛 allow for downloads from private repos

- src/internal/commands/base.rs
- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/config/check.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/config/reshim.rs
- src/internal/commands/builtin/config/trust.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/builtin/hook/base.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/commands/builtin/hook/uuid.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/frompath.rs
- src/internal/commands/loader.rs
- src/internal/commands/utils.rs
- src/internal/config/parser/command_definition.rs
- src/internal/config/parser/errors.rs
- src/internal/config/up/mise.rs
When a command enables the `argparser`, omni will now provide automatically `autocompletion` for that command using the information that was provided to configure the `argparser`. This means that we can auto-complete enum values for instance, as well as all parameters.
New argument types are introduced as `dir`, `file` and `repopath` allowing to respectively auto-complete directories, files and repository paths. When using those types, the value passed to the command will be an absolute path.
Commands that have auto-completion enabled (`true`) will skip the argparser auto-completion. There is also a new `partial` auto-completion that is available when the argparser is configured, if the command provider wants to offer extended auto-completion for the values of specific parameters. The …
> feat(`argparser`): ✨ add auto-completion support

- src/internal/cache/database/sql/up_environments_get_workdir_env.sql
- src/internal/cache/up_environments.rs
- src/internal/config/up/base.rs
When running `omni up`, the `apply environment` would show `done` everytime. This changes that by making it show `already up to date` when the environment did not get updated in any way, indicating that the state before and after `omni up` did not change.
> feat(`up`): ✨ show when the environment is already up to date

- src/internal/commands/builtin/up.rs
- src/internal/config/parser/mod.rs
- src/internal/config/parser/path_repo_updates.rs
- src/internal/env.rs
- src/internal/git/mod.rs
- src/internal/git/updater.rs
By default, `git` updates for a repository are using fast-forward only to avoid breaking anything that the user might have been working on. This requirement does not apply to packages since packages are managed by omni and omni only. We can thus be more aggressive when working in packages by fetching any new commits, and resetting to the origin's branch.
Closes https://github.com/xaf/omni/issues/908
> feat(`packages`): ✨ make git updates more aggressive

- templates/shell_integration.bash.tmpl
This was adding a space when no more completion was available, but the autocompletion command still returned a successful exit code. This is fixed by checking if the autocompletion value is empty and skipping it in this case.
> fix(`shell integration`): 🐛 fix the bash shell integration

- src/internal/commands/base.rs
- src/internal/commands/builtin/cd.rs
- src/internal/commands/builtin/clone.rs
- src/internal/commands/builtin/config/bootstrap.rs
- src/internal/commands/builtin/config/check.rs
- src/internal/commands/builtin/config/path/switch.rs
- src/internal/commands/builtin/config/reshim.rs
- src/internal/commands/builtin/config/trust.rs
- src/internal/commands/builtin/help.rs
- src/internal/commands/builtin/hook/base.rs
- src/internal/commands/builtin/hook/env.rs
- src/internal/commands/builtin/hook/init.rs
- src/internal/commands/builtin/hook/uuid.rs
- src/internal/commands/builtin/scope.rs
- src/internal/commands/builtin/status.rs
- src/internal/commands/builtin/tidy.rs
- src/internal/commands/builtin/up.rs
- src/internal/commands/frompath.rs
This improves the `partial` auto-completion behavior to be usable by commands that were still using the full auto-completion, so that built-in commands only use `partial` or `null` (argparser only) now.
> feat(`argparser`): use `partial` auto-completion for internal commands

- src/internal/commands/base.rs
- src/internal/commands/loader.rs
At this time, the `OMNI_SUBCOMMAND` kept the original value used by the caller before selecting the real command from the `Did you mean?` menu; this led to issues for commands depending on `OMNI_SUBCOMMAND` to show the help, for instance.
This is now fixed as it will set the `OMNI_SUBCOMMAND` environment variable to the selected command in the `Did you mean?` menu.
Fixes https://github.com/xaf/omni/issues/919
> fix(did you mean): `OMNI_SUBCOMMAND` set to selected command

- src/internal/commands/base.rs
- src/internal/commands/builtin/config/check.rs
- src/internal/commands/fromconfig.rs
- src/internal/commands/frompath.rs
- src/internal/commands/loader.rs
- src/internal/config/parser/command_definition.rs
- website/contents/reference/configuration/parameters/commands.md
By adding an omni configuration file in the omnipath, any command it contains that have been flagged for exportation (`export: true`) will now be available as part of the global commands, with the priority corresponding to their position in the omnipath.
This will allow for easier writing of command wrappers for instance, where a shell script wrapper could be replaced by a simple, exported configuration command.
Closes https://github.com/xaf/omni/issues/925
> feat(`config`): configuration commands can be exported in omnipath

- src/internal/commands/builtin/scope.rs
- src/internal/commands/loader.rs
- src/main.rs
The `void commands` are auto-generated commands to be able to show the help when there exist a sub-command, but no command was defined at this level (e.g. `omni a b` is defined, but `omni a` isn't).
So far, calling `omni a --help` or `omni a -h` in that situation would simply fail (and suggest, using `Did you mean?`, to call `omni a b`). This changes that behavior by supporting the special `-h` and `--help` arguments if these are the only ones being passed to a void command, thus triggering to show the help message for that auto-generated command in that situation.
Closes https://github.com/xaf/omni/issues/920
> feat(void command): support `-h` and `--help` for auto-generated commands

- src/internal/cache/github_release.rs
- src/internal/config/parser/github.rs
- src/internal/config/up/github_release.rs
- src/internal/self_updater.rs
Current asset matching only allowed to provide a list of assets without considering the potential need for distinction between operating systems and architecture which might require different rules for the asset name matching.
This fixes that by allowing to provide configuration that matches specific operating systems, architecture or both.
Closes https://github.com/xaf/omni/issues/780
> feat(`github release`): ✨ support for per-os/per-arch asset matching

- src/internal/config/up/github_release.rs
When specifying configuration about which asset to install, we can
end-up with a release at a given version which is very different from
the release at the same version but with patterns to match assets.
This thus allow to distinguish installed github releases if any of the
configuration parameters that would impact the assets being installed is
used. This includes at this time disabling direct-binary-download,
skipping os or arch matching, preferring dist releases, or setting up
any pattern for the asset name.
The version as seen by the user will still be the same, but the install
directory will be suffixed by a `~` and a hash corresponding to the
configuration that was used to install that release.
Closes https://github.com/xaf/omni/issues/934
> feat(`github release`): ✨ distinguish install configurations

- src/internal/dynenv.rs
This was an issue since the move to `mise`.
Closes https://github.com/xaf/omni/issues/938
> fix(`node`): 🐛 dynamic environment was not loaded properly

- src/internal/config/up/mise.rs
`mise` sets up a rubygems plugin to automatically call `mise reshim` when `gem install` operations are called. This is an issue since we do not keep `mise` in the `PATH`. This removes that file after installing ruby versions.
Closes https://github.com/xaf/omni/issues/951
> fix(`ruby`): 🐛 remove `rubygems_plugin.rb` file after mise install

- src/internal/commands/base.rs
- src/internal/commands/builtin/help.rs
- tests/fixtures/omni/help-cd.txt
- tests/fixtures/omni/help-clone.txt
- tests/fixtures/omni/help-config-bootstrap.txt
- tests/fixtures/omni/help-config-check.txt
- tests/fixtures/omni/help-config-path-switch.txt
- tests/fixtures/omni/help-config-reshim.txt
- tests/fixtures/omni/help-config-trust.txt
- tests/fixtures/omni/help-config-untrust.txt
- tests/fixtures/omni/help-down.txt
- tests/fixtures/omni/help-help.txt
- tests/fixtures/omni/help-hook-env.txt
- tests/fixtures/omni/help-hook-init.txt
- tests/fixtures/omni/help-hook-uuid.txt
- tests/fixtures/omni/help-hook.txt
- tests/fixtures/omni/help-scope.txt
- tests/fixtures/omni/help-status.txt
- tests/fixtures/omni/help-tidy.txt
- tests/fixtures/omni/help-up.txt
Those flags exist and are working by default, but weren't showing-up in the help message. This is now fixed.
Closes https://github.com/xaf/omni/issues/937
> feat(`help`): ✨ show `-h`/`--help` flags for argparser-enabled commands

- src/internal/cache/up_environments.rs
- src/internal/config/up/cargo_install.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/go_install.rs
- src/internal/config/up/mise.rs
- src/internal/dynenv.rs
- website/contents/reference/configuration/parameters/up/cargo-install.md
- website/contents/reference/configuration/parameters/up/github-release.md
- website/contents/reference/configuration/parameters/up/go-install.md
The `github-release`, `cargo-install` and `go-install` operations did not support per-directory installation before.
By adding a `dir` parameter to any entry in those operations, we can now scope the subdirectory in which it will be installed.
Closes https://github.com/xaf/omni/issues/882
> feat: ✨ extend `dir` support

- src/internal/git/updater.rs
The pre-auth was still happening for hosts even if there is an exception to not update the specific repositories. This fixes that by disabling the pre-auth when no updater will be returned.
Closes https://github.com/xaf/omni/issues/1037
> fix(pre-auth): do not pre-auth when update is disabled

- Cargo.toml
- src/internal/build.rs
- src/internal/cache/github_release.rs
- src/internal/config/parser/path_repo_updates.rs
- src/internal/config/up/github_release.rs
- src/internal/env.rs
- src/internal/mod.rs
- src/internal/self_updater.rs
This introduces support for disabling self-updates entirely at compile time, or compiling omni for defaulting to not check for new updates.
This also introduces support for versioned brew formulas, and disabling self-updates automatically if omni was installed through a versioned formula.
> feat(self-update): support disabled updates

- .omni.yaml
- src/internal/cache/up_environments_test.rs
- src/internal/config/up/mise.rs
- src/internal/git/mod.rs
- src/internal/git/utils.rs
- src/internal/git/utils_test.rs
- src/internal/testutils.rs
Omni already handles the global gitignore on top of the local gitignore, but when a subdirectory of a workdir is a git repository, the gitignore ends-up being checked from the most specific git repository, and not necessarily the one corresponding to the omni workdir.
This fixes that by passing down the workdir root path to be used as git-base, if in a git workdir.
Closes https://github.com/xaf/omni/issues/1143
> feat(gitignore): handle ignoring from workdir root
