xaf/omni

- .github/workflows/tests.yaml
- install.sh
Adding `install.sh` support for Fedora users
> 🤠 install.sh: adding fedora support

- website/contents/tutorials/02-get-started/0202-initial-configuration.md
- website/contents/tutorials/03-set-up-a-repository/0301-up-configuration.md
> 📝 Small tutorial typo corrections

- src/internal/self_updater.rs
- website/contents/reference/01-configuration/0103-environment.md
Fixes https://github.com/XaF/omni/issues/142
> fix: 🐛 self update now replaces  current process

- website/package.json
- website/yarn.lock
- [`@docusaurus/core`](https://www.npmjs.com/package/@docusaurus/core) ([`v2.4.3`](https://www.npmjs.com/package/@docusaurus/core/v/2.4.3) -> [`v3.0.0`](https://www.npmjs.com/package/@docusaurus/core/v/3.0.0))
- [`@docusaurus/module-type-aliases`](https://www.npmjs.com/package/@docusaurus/module-type-aliases) ([`v2.4.3`](https://www.npmjs.com/package/@docusaurus/module-type-aliases/v/2.4.3) -> [`v3.0.0`](https://www.npmjs.com/package/@docusaurus/module-type-aliases/v/3.0.0))
- [`@docusaurus/preset-classic`](https://www.npmjs.com/package/@docusaurus/preset-classic) ([`v2.4.3`](https://www.npmjs.com/package/@docusaurus/preset-classic/v/2.4.3) -> [`v3.0.0`](https://www.npmjs.com/package/@docusaurus/preset-classic/v/3.0.0))
- [`@mdx-js/react`](https://www.npmjs.com/package/@mdx-js/react) …
> chore(deps): 📦 yarn update

- src/internal/commands/builtin/status.rs
`omni status` now takes arguments to show different elements of the status, and does not show the configuration by default anymore.
Closes https://github.com/XaF/omni/issues/180
> feat(status): ✨ now takes arguments

- src/internal/commands/builtin/config/bootstrap.rs
When bootstrapping, if only selecting organizations, there is no need for the ordering step. This makes it skip it.
Closes https://github.com/XaF/omni/issues/290
> feat(bootstrap): ✨ Do not ask to order orgs if only one

- src/internal/config/config_value.rs
Fixes https://github.com/XaF/omni/issues/360
> fix(config value): 🐛 missing check made the tool panic

- .github/workflows/tests.yaml
- shell_integration/omni.bash.tmpl
- src/internal/cache/handler.rs
- src/internal/commands/builtin/cd.rs
- src/internal/config/config_value.rs
- tests/test_omni_help.bats
Fixes https://github.com/XaF/omni/issues/416
> fix(cd): autocompletion for / and ~/ paths

- src/internal/cache/homebrew_operation.rs
- src/internal/commands/frompath.rs
- src/internal/config/up/homebrew.rs
- src/internal/config/utils.rs
- src/internal/env.rs
- src/internal/self_updater.rs
Closes https://github.com/XaF/omni/issues/417
> feat(homebrew): detecting cask bin directories

- src/internal/cache/homebrew_operation.rs
- src/internal/config/up/base.rs
- src/internal/config/up/homebrew.rs
- src/internal/config/up/nix.rs
This allows to handle proper homebrew cleanup for formulas and taps that have been installed by omni, during any resource cleanup step.
Closes https://github.com/XaF/omni/issues/434
> feat(homebrew): ✨ handle proper cleanup

- src/internal/config/up/asdf_base.rs
The `gdbm` nix dependency was missing to install python. Also, the `DESTDIR` and `INSTALL_PREFIX` environment variables are confusing the asdf installed if present on the system, so we make sure to clear them before calling any asdf command.
> fix(asdf): 🐛 add missing dependency for Python and clear env vars

- src/internal/config/up/utils.rs
- src/internal/git/updater.rs
- tests/test_omni_up_python.bats
Following https://github.com/XaF/omni/pull/456, we can handle password requests during `omni up`. This makes it handle password requests from `git pull` / `git fetch` during repository updates.
Closes https://github.com/XaF/omni/issues/160
> feat(git): ✨ handle askpass for git updates

- src/internal/config/up/github_release.rs
This returns a properly-formatted error message if there is an issue while trying to download the releases.
> fix(github-release): 🐛 handle GitHub request errors better

- src/internal/self_updater.rs
The homebrew update was failing when homebrew auto update is disabled but there was no indicator this was the case, with omni reporting that the update went through.
This fixes that by checking the version of omni after an upgrade by calling `omni --version` and checking that the version installed corresponds to the version we were trying to install.
> fix(self update): 🐛 check version after successful update

- website/contents/reference/02-builtin-commands/0250-hook.md
- website/contents/tutorials/02-get-started/0201-install.md
- website/contents/tutorials/04-ide-integration.md
- website/docusaurus.config.js
Closes https://github.com/XaF/omni/issues/499
> docs(shims): 📝 add documentation around shims and IDEs

- src/internal/commands/builtin/up.rs
The `auto-bootstrap` aspect of omni was not checking for non-interactive shells, triggering suggestions. On top of that, setting `--clone-suggested no` or `--update-user-config no` did not override the auto-bootstrap, preventing to disable the feature outside of the configuration itself.
> fix(up): 🐛 auto-bootstrap disabled on non-interactive shells

- src/internal/config/template.rs
- src/internal/config/up/utils/askpass.rs
- src/internal/config/up/utils/progress_handler.rs
- templates/askpass.sh.tmpl
This now allows the GUI to show the command that requested authentication, and adds a button to get details about the command that omni attempted to run initially, that might have triggered this prompt.
Closes https://github.com/XaF/omni/issues/579
> feat(askpass): show command requiring authentication

- src/internal/commands/builtin/up.rs
- src/internal/env.rs
This will allow to run `omni up` when being called with `--update-repository` even if there were no update during `git pull`. This could happen if using a worktree repository or if the previous `omni up` was canceled (Ctrl+C) after the update of the repository.
Closes https://github.com/XaF/omni/issues/575
> feat(up): save last `up` head commit

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
Closes https://github.com/XaF/omni/issues/615
> build(attestation): 👷 attest build provenance on release

- src/internal/config/up/python.rs
Instead of dealing manually with the serialization, this allows to properly merge the asdf base struct with the python-specific parameters.
> refactor(python): ♻️  handle params as separate struct

- src/internal/self_updater.rs
Closes https://github.com/XaF/omni/issues/646
> chore(variant): add 'osx' as a variant of darwin

- tests/test_config_commands.bats
These were written for https://github.com/XaF/omni/pull/735 but weren't committed
> tests(config command): add missing bats tests

- website/contents/tutorials/05-cicd.md
This includes reference to the GitHub Action.
Closes https://github.com/XaF/omni/issues/491
> docs(ci/cd): 📝 add documentation on using omni in CI/CD

- src/internal/cache/github_release.rs
- src/internal/config/up/github_release.rs
- src/internal/config/up/go_install.rs
Closes https://github.com/XaF/omni/issues/862
> fix(`github-releases`): add support for pagination when using the API

- src/internal/config/up/mise.rs
Closes https://github.com/XaF/omni/issues/789
> feat(`auto`): ignore .gitignore'd directories when using `auto`

- src/internal/commands/builtin/config/check.rs
- src/internal/config/config_value.rs
- src/internal/config/parser/check.rs
- src/internal/config/parser/mod.rs
- src/internal/config/parser/omniconfig.rs
- website/contents/reference/builtin-commands/overview.md
- website/contents/reference/configuration/parameters/check.md
This adds a configuration entry `check` to indicate the errors to select/ignore and the patterns to match when running `omni config check`.
Closes https://github.com/XaF/omni/issues/867
> feat(`config check`): ✨ add configuration

- src/internal/cache/github_release.rs
`dist` releases can contain a ton of extra files that don't make sense to have around if we just want to get some binary tool. This will ensure that `dist` releases are a lower priority than non-dist ones, and thus limit the size of the downloads too.
Closes https://github.com/XaF/omni/issues/892
> feat(`github-release`): ✨ prioritize non-dist releases

- src/internal/config/up/go_install.rs
When using the `go` binary to run `go install`, we need to have properly setup `GOROOT` and `GOVERSION` environment variables in order for the installation to work. This adds a wrapper to create the commands which will add those variables automatically.
> fix(`go-install`): 🐛 add `GOROOT` and `GOVERSION` env vars for bin

- src/internal/git/updater.rs
This will allow to refresh a package to the last commit all the time during updates.
Closes https://github.com/xaf/omni/issues/918
> feat(`package`): ✨ use `git rev-list` to check if packages are up to date

- .github/scripts/get-changed-files.sh
- .github/workflows/tests.yaml
See: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
> chore(security): 🔒 remove tj-actions/changed-files

- src/internal/dynenv.rs
This will allow for commands like `uv sync` and `uv add` to work seamlessly in the omni-managed virtual environment.
> feat(`python`): ✨ set `UV_PROJECT_ENVIRONMENT` in dynamic environment

- src/internal/config/up/github_release.rs
This change ensures the GitHub CLI (`cli/cli`) is installed first when multiple GitHub releases are configured and it is provided in the list, and reloads the environment between release installations to ensure proper environment variables are available for each subsequent release (including specifically for `gh` to be available).
Closes https://github.com/xaf/omni/issues/1051
> feat(github-release): ✨ prioritize `gh` cli and reload env between releases

- src/internal/config/up/utils/version.rs
This adds support for versions specified in a `pyproject.toml` that are split by commas.
> versions: support pyproject.toml versions better
